name: Docker Build and Push

on:
  push:
    branches:
      - main  # This workflow will be triggered by push events on the main branch. Change if needed.

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # This workflow will run on an Ubuntu machine

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main  # Ensure you are working with the 'main' branch

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Secret for your Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # Secret for your Docker Hub password or access token

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t projnajit/temp2:latest .  # Build the image and tag it with 'latest'

      # Step 5: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push projnajit/temp2:latest  # Push the image to Docker Hub under 'projnajit/temp2:latest'
